### PR TITLE
Add function to ignore certain events + easter egg

### PR DESCRIPTION
**Pull request by mcornella**
I just have too much free time ¯\\\_\(ツ\)_/¯

Feel free to ignore the easter egg but I think the filter function could be useful in a future if you want to add filters. I love the simplicity of the website though so it's fine if you don't want to add this.

Love the project! :heart:

----
##### Add function to ignore events:

This commit adds a filter function for events that should be ignored, which can be extended later via a commit or a DevTools hack.

##### Add easter egg to only play closed PRs:

To use this, just set `ULTIMATE_DREAM_KILLER` in your DevTools console. 

The explanation for this easter egg can be found [in this article](https://blog.jessfraz.com/post/the-art-of-closing/). Just look for `Ultimate Dream Killers`. Some people just like to see other people's dreams crushed :-1:

### CODE REVIEW

**Comment by debugger22** [comment]
@mcornella Thank you for doing this!

**Comment by mcornella** [comment]
Oh the easter egg still needs to reset the `eventQueue`.  :disappointed:

**Comment by debugger22** [comment]
I didn't test it. And yeah, `ULTIMATE_DREAM_KILLER` had to be initialised first which I did.

**Comment by debugger22** [comment]
@mcornella The oh-my-zsh is super cool! It's my default terminal now.

**Comment by mcornella** [comment]
Oh wow! That makes me very happy! :smile: 

I have a solution to the queue problem, will push a PR soon :)

**Pull request merged**
